# Generated by Django 4.1.3 on 2022-11-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_student_email_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
