# Generated by Django 4.1.3 on 2022-11-22 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$')])),
                ('duration', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(30, message='Minimum value of 30 minutes not set.')])),
                ('date', models.DateField()),
                ('price', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, message='Price field must be set to a value greater than zero.')])),
            ],
        ),
    ]
